# Generated by Django 3.0.8 on 2020-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type_budget', models.CharField(choices=[('budget', 'budget'), ('glavbudget', 'glavbudget')], default='budget', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ссылка для запроса',
                'verbose_name_plural': 'Ссылки для запросов',
            },
        ),
    ]
